### PR TITLE
Require that Cargo.lock is up to date 

### PR DESCRIPTION
**Pull request by sreenathkrishnan**

### CODE REVIEW

**Comment by DavidBJaffe** [comment]
This seems like a reasonable requirement.  There is a release "script"
`enclone/enclone/src/bin/start_release.rs`.  Will this still work after the change?
My reason for concern is that a release always leaves the repo in a state where 
`Cargo.lock` needs to be updated.

**Comment by sreenathkrishnan** [comment]
Ah, that's the script that bumps up the version. It would be good to `cargo check` and `git add Cargo.lock` in that script. We seem to often get into a state in enclone master where the Cargo.lock is not up to date.

**Comment by DavidBJaffe** [comment]
I am confused as to where in the script that would go.

**Comment by DavidBJaffe** [comment]
I am going to try to fix the problem in the release script.

**Comment by sreenathkrishnan** [comment]
Cool -- I took a quick look at the script. The cargo.lock needs to be updated after bumping up the versions (say, by running `cargo b`). It would then by picked up by the `git commit`

**Comment by wyattmcdonnell** [comment]
Superseded by #164.

**Pull request closed without merging**
