### PR TITLE
Make Visual Optional

### PR DESCRIPTION
**Pull request by evolvedmicrobe**
Enable enclone to be compiled without the GUI dependencies.  Will enable faster compilation of CLI tools and possibly allow CI to pass.

### CODE REVIEW

**Comment by DavidBJaffe** [comment]
I would much prefer that we fix the CI.  The visual code is as much part of enclone as many other
parts of it/

**Comment by evolvedmicrobe** [comment]
`I would much prefer that we fix the CI. The visual code is as much part of enclone as many other parts of it.`

Honestly, I think trying to get a GUI to work on Linux is often a fools errand (having been such a fool many years ago).  It might be useful to break out the `server` code from the `visual` code so that you can test that aspect on the internal infrastructure though.

CI passing!

**Comment by evolvedmicrobe** [comment]
`How about leaving the GitHub Actions tests as is, and turning off enclone visual just for the Jenkins tests? `

Yeah, we can make it opt-out instead of opt-in, updated the PR.

**Comment by DavidBJaffe** [comment]
And awesome that Jenkins passes now!

**Pull request merged**
