### PR TITLE
miscellaneous things

### PR DESCRIPTION
**Pull request by DavidBJaffe**
1. Try to fix the problem with `Cargo.lock` being out of date after a release.

2. Upon panicking, print the command, and also send flowers:
🌸 Thank you and have a nice day! 🌸
When in doubt, send flowers.

3. Recompute CDR3, rather than take the values in `all_contig_annotations.json`.  This changes the values at a very
low rate, and only if the CDR3 computation was changed between the time of the `cellranger` release and that of 
the `enclone` release.  Otherwise, internal inconsistencies can cause asserts.

### CODE REVIEW

**Comment by DavidBJaffe** [comment]
jenkins retest this please

**Comment by DavidBJaffe** [comment]
jenkins retest this please

**Comment by DavidBJaffe** [comment]
jenkins retest this please

**Comment by DavidBJaffe** [comment]
jenkins retest this please

**Review by wyattmcdonnell — APPROVED** [review]
Good to go other than the testing issue, which is a separate problem. Thanks!!

**Pull request merged**
