### PR TITLE
Run cargo clippy --fix.

### PR DESCRIPTION
**Pull request by adam-azarchs**
Only touch enclone_ranger and its dependencies, revert the rest.

These automated fixups help with a bunch of run-time and compiile-time
inefficiencies.

### CODE REVIEW

**Comment by DavidBJaffe** [comment]
The files proc_cvar_auto.rs and proc_lvar_auto.rs cannot be modified in this way because they are auto-generated.

**Comment by DavidBJaffe** [comment]
How can I check this branch out locally?  I get merge conflicts when I try.

**Comment by adam-azarchs** [comment]
There are no merge conflicts with master...  `git checkout azarchs/clippy` should work unless you have a dirty work tree.  Not sure why you'd need to check it out though, since it's passed CI.

**Comment by adam-azarchs** [comment]
If you want to check out the merge commit,
```
git fetch origin +refs/pull/373/merge && git checkout FETCH_HEAD
```

**Comment by adam-azarchs** [comment]
(if your plan was to benchmark compile times, don't bother.  The difference will not be measurable when building enclone on its own)

**Comment by DavidBJaffe** [comment]
Thanks for the command.  There are tests that are not in the CI and can't easily be put there.  They are unlikely to fail but I prefer to be extra cautious and run them, in cases where I don't fully understand the PR content.  They passed, so all good.

**Review by DavidBJaffe — APPROVED** [review]

**Comment by adam-azarchs** [comment]
I would note that `clippy` actually provides quite good documentation explaining for each lint why the warned-on behavior is bad, what the preferred alternative should be, and the circumstances under which it may be safe to ignore it.  A selection of ones fixed in this PR:
https://rust-lang.github.io/rust-clippy/master/#collapsible_else_if
https://rust-lang.github.io/rust-clippy/master/#collapsible_if
https://rust-lang.github.io/rust-clippy/master/#needless_borrow
https://rust-lang.github.io/rust-clippy/master/#needless_bool
https://rust-lang.github.io/rust-clippy/master/#needless_return
https://rust-lang.github.io/rust-clippy/master/#redundant_closure
https://rust-lang.github.io/rust-clippy/master/#redundant_field_names
https://rust-lang.github.io/rust-clippy/master/#single_char_pattern
https://rust-lang.github.io/rust-clippy/master/#stable_sort_primitive
https://rust-lang.github.io/rust-clippy/master/#unnecessary_cast
https://rust-lang.github.io/rust-clippy/master/#unnecessary_mut_passed
https://rust-lang.github.io/rust-clippy/master/#useless_format

`clippy --fix` will fix any lint that is denied or a warning and is marked as "Applicability: `MachineApplicable`".

**Pull request merged**
