### PR TITLE
Widen version ranges of prost and bytes.

### PR DESCRIPTION
**Pull request by adam-azarchs**
This allows downstream crates to update their dependencies, and also
gets rid of the duplicated version of itertools.

Next up, petgraph and ndarray...

### CODE REVIEW

**Review by sreenathkrishnan — APPROVED** [review]
Cool!
(Not sure why the jenkins build failed though)

**Comment by DavidBJaffe** [comment]
The Jenkins fail is as best I can tell a stochastic file access problem.  So maybe the fault of the environment, and totally unrelated to this PR.  It is a recurring problem and maybe I don't understand it.

**Comment by adam-azarchs** [comment]
jenkins retest this please?

**Comment by DavidBJaffe** [comment]
Current master has a fix that probably resolves the stochastic failure problem that occurred on this PR.

**Pull request merged**
