### PR TITLE
ensure that remote version file has group write permission

### PR DESCRIPTION
**Pull request by DavidBJaffe**

### CODE REVIEW

**Comment by DavidBJaffe** [comment]
release_nanny is part of the enclone release process.  It uses a file that contains the current version.  That gets updated when here is a release.  The file needs to have group write permission and this commit forces that to be true.

**Comment by DavidBJaffe** [comment]
I don't know why the Jenkins test is failing.  I do not have visibility of it.  It should not be failing.

**Comment by wyattmcdonnell** [comment]
Jenkins retest this please

**Comment by wyattmcdonnell** [comment]
No idea why Jenkins failed on this, [but it passes with no difficulties on my identical PR](https://github.com/10XGenomics/enclone/pull/482), which I'm merging now. Thank you!

**Pull request closed without merging**
